FROM ubuntu:22.04

RUN apt-get update && \
    apt-get -y install bash && \
    apt-get -y install cppcheck

COPY test1.sh /usr/local/bin/vuln

RUN chmod +x /usr/local/bin/vuln

ENTRYPOINT ["/usr/local/bin/vuln"]

